"""``marginalia serve`` — tiny HTTP capture endpoint (design Phase 3.8).

A localhost-only HTTP server that exposes ``POST /add`` so a browser
extension (or any URL-poster like ``curl``) can trigger
``marginalia add`` without spawning a CLI subprocess. Built on
``http.server`` to avoid pulling FastAPI as a dep — the contract is
one endpoint, two error paths, and a token check.

Security model:

- Default binding: 127.0.0.1:7777. Never exposed to the network
  without the explicit ``--host`` flag.
- Auth: token in ``Authorization: Bearer <token>`` header. Token is
  generated by ``marginalia serve --init-token`` and stored at
  ``~/.config/marginalia/serve.token`` (mode 0600). Every request
  validates against the stored token; wrong/missing → 401.
- The token is a 32-byte random hex string — long enough that brute
  force is irrelevant on a localhost binding.

Lifecycle:

  $ marginalia serve --init-token       # one-time setup
  Token written to ~/.config/marginalia/serve.token
  $ marginalia serve                    # start listening
  $ curl -X POST http://127.0.0.1:7777/add \
      -H "Authorization: Bearer $(cat ~/.config/marginalia/serve.token)" \
      -d '{"target": "https://example.com/article"}'
  {"ok": true, "staged": "/path/to/inbox/example-com-abc12345.url"}
"""

from __future__ import annotations

import contextlib
import json
import secrets
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

import typer
from rich.console import Console

from engine.cli.capture import StageError, stage_target

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 7777
DEFAULT_TOKEN_PATH = Path.home() / ".config" / "marginalia" / "serve.token"
TOKEN_BYTES = 32  # 64 hex chars after secrets.token_hex(32)
MAX_BODY_BYTES = 4096  # POST bodies are tiny — refuse anything larger as a guardrail

app = typer.Typer(
    name="serve",
    help="Run an HTTP capture endpoint that browser extensions can POST to.",
    no_args_is_help=False,
    invoke_without_command=True,
)
console = Console()


def _resolve_token_path(explicit: Path | None) -> Path:
    return explicit or DEFAULT_TOKEN_PATH


def _ensure_token_dir(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def _write_token(path: Path) -> str:
    """Generate a fresh 64-char hex token and write it (mode 0600)."""
    token = secrets.token_hex(TOKEN_BYTES)
    _ensure_token_dir(path)
    path.write_text(token + "\n", encoding="utf-8")
    # Restrict to user-only read/write — the token is equivalent to
    # ingest authority on this wiki. On Windows filesystems chmod is
    # a no-op; the directory permissions still gate access in practice.
    with contextlib.suppress(OSError):
        path.chmod(0o600)
    return token


def _read_token(path: Path) -> str | None:
    if not path.is_file():
        return None
    return path.read_text(encoding="utf-8").strip() or None


def _make_handler_class(*, expected_token: str):
    """Build the handler class with the auth token closed over.

    Closure over ``expected_token`` rather than a module global so
    multiple servers (tests, dev) don't trip over each other.
    """

    class _AddHandler(BaseHTTPRequestHandler):
        # ``http.server`` defaults log every request to stderr in a noisy
        # format. Override to a quieter line for "serve" use cases.
        def log_message(self, format: str, *args) -> None:
            console.print(f"[dim]{self.address_string()} - {format % args}[/dim]")

        def _send_json(self, status: HTTPStatus, payload: dict) -> None:
            body = json.dumps(payload).encode("utf-8")
            self.send_response(int(status))
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            # Chrome extensions making fetch() calls need CORS — allow
            # localhost origins explicitly. Browser extensions calling
            # localhost from chrome-extension:// work fine without CORS;
            # this header serves bookmarklets and dev tooling.
            self.send_header("Access-Control-Allow-Origin", "*")
            self.send_header("Access-Control-Allow-Headers", "Authorization, Content-Type")
            self.send_header("Access-Control-Allow-Methods", "POST, OPTIONS")
            self.end_headers()
            self.wfile.write(body)

        def _check_auth(self) -> bool:
            header = self.headers.get("Authorization", "")
            prefix = "Bearer "
            if not header.startswith(prefix):
                self._send_json(
                    HTTPStatus.UNAUTHORIZED,
                    {"ok": False, "error": "missing or malformed Authorization header"},
                )
                return False
            # ``secrets.compare_digest`` resists timing attacks.
            if not secrets.compare_digest(header[len(prefix) :], expected_token):
                self._send_json(
                    HTTPStatus.UNAUTHORIZED,
                    {"ok": False, "error": "invalid token"},
                )
                return False
            return True

        def do_OPTIONS(self) -> None:  # noqa: N802 — http.server convention
            """Preflight for CORS."""
            self.send_response(int(HTTPStatus.NO_CONTENT))
            self.send_header("Access-Control-Allow-Origin", "*")
            self.send_header("Access-Control-Allow-Headers", "Authorization, Content-Type")
            self.send_header("Access-Control-Allow-Methods", "POST, OPTIONS")
            self.end_headers()

        def do_POST(self) -> None:  # noqa: N802 — http.server convention
            if self.path != "/add":
                self._send_json(
                    HTTPStatus.NOT_FOUND, {"ok": False, "error": f"unknown path {self.path!r}"}
                )
                return

            if not self._check_auth():
                return

            length = int(self.headers.get("Content-Length", "0") or "0")
            if length > MAX_BODY_BYTES:
                self._send_json(
                    HTTPStatus.REQUEST_ENTITY_TOO_LARGE,
                    {"ok": False, "error": f"body too large (max {MAX_BODY_BYTES} bytes)"},
                )
                return

            raw = self.rfile.read(length) if length else b""
            try:
                payload = json.loads(raw or b"{}")
            except json.JSONDecodeError as exc:
                self._send_json(
                    HTTPStatus.BAD_REQUEST,
                    {"ok": False, "error": f"invalid JSON: {exc}"},
                )
                return

            target = (payload.get("target") or "").strip()
            force = bool(payload.get("force", False))
            if not target:
                self._send_json(
                    HTTPStatus.BAD_REQUEST,
                    {"ok": False, "error": "missing 'target' field"},
                )
                return

            try:
                staged_path = stage_target(target, force=force)
            except StageError as exc:
                # 409 Conflict for "already staged" — the client may
                # want to retry with force=true. 400 for other failures.
                msg = str(exc)
                status = HTTPStatus.CONFLICT if "already" in msg else HTTPStatus.BAD_REQUEST
                self._send_json(status, {"ok": False, "error": msg})
                return

            self._send_json(
                HTTPStatus.OK,
                {"ok": True, "staged": str(staged_path)},
            )

        def do_GET(self) -> None:  # noqa: N802
            """Health check at GET / — no auth required (returns just status)."""
            if self.path != "/":
                self._send_json(HTTPStatus.NOT_FOUND, {"ok": False, "error": "not found"})
                return
            self._send_json(HTTPStatus.OK, {"ok": True, "service": "marginalia-serve"})

    return _AddHandler


@app.callback()
def main(
    init_token: bool = typer.Option(
        False,
        "--init-token",
        help="Generate a fresh auth token, write it, and exit. Run this first.",
    ),
    host: str = typer.Option(
        DEFAULT_HOST,
        "--host",
        help="Bind address. Default 127.0.0.1 (localhost only); set to 0.0.0.0 to expose.",
    ),
    port: int = typer.Option(
        DEFAULT_PORT,
        "--port",
        help="TCP port to listen on.",
    ),
    token_path: Path = typer.Option(  # noqa: B008
        None,
        "--token-path",
        help="Where to read/write the auth token. Default ~/.config/marginalia/serve.token.",
    ),
) -> None:
    """Run the HTTP capture endpoint."""
    path = _resolve_token_path(token_path)

    if init_token:
        token = _write_token(path)
        console.print(f"[green]wrote token[/green] → {path}")
        console.print("[dim](mode 0600; copy this into your browser extension)[/dim]")
        console.print(token)
        raise typer.Exit(code=0)

    token = _read_token(path)
    if not token:
        console.print(
            f"[red]no token at {path}[/red]; run [cyan]marginalia serve --init-token[/cyan] first"
        )
        raise typer.Exit(code=1)

    if host != "127.0.0.1" and host != "localhost":
        console.print(
            f"[yellow]binding to {host}:{port} — ensure your firewall is configured.[/yellow]"
        )

    handler_cls = _make_handler_class(expected_token=token)
    server = ThreadingHTTPServer((host, port), handler_cls)
    console.print(
        f"[green]marginalia serve[/green] listening on http://{host}:{port}/add "
        f"[dim](Ctrl-C to stop)[/dim]"
    )
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        console.print("\n[dim]shutting down…[/dim]")
        server.shutdown()


__all__ = [
    "DEFAULT_HOST",
    "DEFAULT_PORT",
    "DEFAULT_TOKEN_PATH",
    "MAX_BODY_BYTES",
    "TOKEN_BYTES",
    "app",
]


# ─── helpers exported for tests ────────────────────────────────────


def _build_handler_for_tests(token: str):
    """Return the handler class bound to ``token``. Used by test_serve.py.

    Exposed because building a real ThreadingHTTPServer in tests is
    flaky (port races, async cleanup). Tests construct a request
    inline and call the handler's methods directly.
    """
    return _make_handler_class(expected_token=token)
